# Generated by Django 2.2 on 2020-02-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200210_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsettings',
            name='allow_comment',
            field=models.BooleanField(choices=[(False, '禁用评论'), (True, '启用评论')], default=False, verbose_name='是否可以评论'),
        ),
    ]
