# Generated by Django 2.2 on 2020-02-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_bloguser_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='label',
            field=models.ForeignKey(on_delete=None, to='blog.BlogLabel', verbose_name='标签'),
        ),
    ]
