# Generated by Django 2.2 on 2020-02-13 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200213_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='label',
        ),
    ]
