# Generated by Django 2.2 on 2020-02-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blogarticle_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='label',
            field=models.CharField(default='', max_length=500, verbose_name='标签'),
        ),
    ]
