# Generated by Django 2.2 on 2020-02-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogarticle_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('sort_id', models.IntegerField(default=1, verbose_name='排序')),
            ],
            options={
                'verbose_name': '独立页面',
                'verbose_name_plural': '独立页面',
            },
        ),
    ]
