# Generated by Django 2.2 on 2020-02-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='is_draft',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], default=True, verbose_name='是否草稿'),
        ),
    ]
