# Generated by Django 2.2 on 2020-02-16 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpage_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='update_time',
            field=models.DateTimeField(null=True, verbose_name='修改时间'),
        ),
    ]
