# Generated by Django 2.2 on 2020-02-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200216_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='update_time',
            field=models.DateTimeField(verbose_name='修改时间'),
        ),
    ]
