# Generated by Django 2.2 on 2020-02-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200216_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='email',
            field=models.EmailField(default='282465134@qq.com', max_length=254, verbose_name='游客邮箱'),
        ),
    ]
