# Generated by Django 2.2 on 2020-02-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_articlecomment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='游客邮箱'),
        ),
    ]
